# Generated by Django 6.1 on 2026-08-15 05:22

import deals.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("brand_key", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("brand", models.CharField(max_length=80)),
                ("category", models.CharField(default="general", max_length=50)),
            ],
            options={
                "ordering": ["brand"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.CharField(max_length=40, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("network", models.CharField(max_length=40)),
                ("base_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("bonus_category", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bonus_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "reward_cap",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("annual_fee", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SearchRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=deals.models.search_id, editable=False, max_length=40, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("brand", models.CharField(max_length=80)),
                ("brand_key", models.CharField(db_index=True, max_length=80)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("strategy", models.CharField(max_length=32)),
                ("result_count", models.IntegerField(default=0)),
                ("best_pick_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "best_pick_effective_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("cache_hit", models.BooleanField(default=False)),
                ("latency_ms", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=deals.models.deal_id, editable=False, max_length=40, unique=True
                    ),
                ),
                ("brand", models.CharField(max_length=80)),
                ("brand_key", models.CharField(db_index=True, max_length=80)),
                ("title", models.CharField(max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("offer", "Offer"),
                            ("coupon", "Coupon"),
                            ("cashback", "Cashback"),
                            ("card_reward", "Card reward"),
                        ],
                        max_length=20,
                    ),
                ),
                ("discount_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "max_discount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("min_spend", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("category", models.CharField(default="general", max_length=50)),
                ("feeds", models.CharField(default="", max_length=120)),
                ("dedupe_key", models.CharField(max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["brand_key", "source", "-discount_pct"],
                "indexes": [
                    models.Index(
                        fields=["brand_key", "min_spend"], name="deals_deal_brand_k_d2e525_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("endpoint", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("status_code", models.IntegerField()),
                ("response_body", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="deals_idemp_created_a97333_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "endpoint"), name="uniq_key_per_endpoint"
                    )
                ],
            },
        ),
    ]
